import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar is generated from the directory tree, so adding a page is adding
// a file. Ordering comes from `sidebar_position` in each page's front matter
// and from the `_category_.json` files.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {type: 'autogenerated', dirName: '.'},
    // The two standalone pages, linked rather than moved. They live at
    // `/privacy` and `/terms` outside `docs/` because those are the URLs
    // Google's Branding form points at, and a policy whose address changes is
    // a policy somebody has to go and re-enter. Linking keeps the addresses
    // fixed and still puts them where a reader looks for them.
    {
      type: 'category',
      label: 'Legal',
      collapsed: true,
      items: [
        {type: 'link', label: 'Privacy policy', href: '/privacy'},
        {type: 'link', label: 'Terms of service', href: '/terms'},
      ],
    },
  ],
};

export default sidebars;
