import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar is generated from the directory tree, so adding a page is adding
// a file. Ordering comes from `sidebar_position` in each page's front matter
// and from the `_category_.json` files.
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
